global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'discord-bot'
    static_configs:
      - targets: ['discord-bot:8000']
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
