name: Deploy to EC2

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
      
      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.EC2_HOST }} "
            # Create a deployment directory with timestamp
            DEPLOY_DIR=~/deployments/$(date +%Y%m%d_%H%M%S)
            mkdir -p \$DEPLOY_DIR
            cd \$DEPLOY_DIR
            
            # Clone the repository
            git clone ${{ github.server_url }}/${{ github.repository }}.git .
            
            # Set up environment variables
            echo '${{ secrets.ENV_FILE }}' > .env
            
            # Deploy with Docker Compose
            docker-compose down || true
            docker-compose pull
            docker-compose up -d
            
            echo 'Deployment completed successfully!'
          "